/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TenantSettings, Party, Transaction, AuditLog } from './types';

export const defaultTenant: TenantSettings = {
  id: 'tenant-1',
  name: 'Apex Solutions Corp',
  baseCurrency: 'USD',
  fiscalYearStartMonth: 7, // July 1 - June 30 fiscal year
  transactionNumbering: {
    invoice: 'INV-2026-',
    bill: 'BIL-2026-',
    payment_received: 'PMR-2026-',
    payment_made: 'PMM-2026-',
    advance: 'ADV-2026-',
    milestone_invoice: 'MSI-2026-',
    retainer: 'RET-2026-',
    credit_note: 'CRN-2026-',
    debit_note: 'DBN-2026-',
    journal_adjustment: 'JV-2026-',
    opening_balance: 'OPR-2026-',
  },
  approvalThreshold: 8000, // Entries > $8000 require approval
  customFields: [
    {
      id: 'party-risk-rating',
      label: 'Risk Rating',
      type: 'dropdown',
      options: ['Low', 'Medium', 'High', 'Critical'],
      target: 'party',
    },
    {
      id: 'txn-cost-center',
      label: 'Cost Center',
      type: 'dropdown',
      options: ['Delivery Unit 1', 'Engineering Services', 'Creative Dept', 'Marketing Ops'],
      target: 'transaction',
    },
  ],
  branches: [
    { id: 'b-ny', name: 'New York HQ', code: 'NY' },
    { id: 'b-ldn', name: 'London Office', code: 'LDN' },
    { id: 'b-dxb', name: 'Dubai Hub', code: 'DXB' },
  ],
  lockDate: '2026-03-31', // Past lock date
};

export const seedParties: Party[] = [
  {
    id: 'p-acme',
    name: 'Acme Enterprise Consulting',
    code: 'CLI-ACME',
    type: 'client',
    status: 'active',
    baseCurrency: 'USD',
    taxId: 'US-9920192',
    creditLimit: 120000,
    paymentTermsDays: 30,
    contacts: [
      { id: 'c-1', name: 'Sarah Jenkins', role: 'VP Accounts', phone: '+1 555-019-2831', email: 'sjenkins@acme.com' },
      { id: 'c-2', name: 'Robert Chen', role: 'Engineering Lead', phone: '+1 555-019-4820', email: 'rchen@acme.com' },
    ],
    projects: [
      {
        id: 'proj-acme-cloud',
        name: 'Cloud Infrastructure Upgrade',
        milestones: [
          { id: 'm-acme-1', name: 'Phase 1: Architecture Blueprint', amount: 15000, status: 'billed' },
          { id: 'm-acme-2', name: 'Phase 2: Core Migration', amount: 25000, status: 'billed' },
          { id: 'm-acme-3', name: 'Phase 3: Integration & QA', amount: 20000, status: 'open' },
          { id: 'm-acme-4', name: 'Phase 4: Global Rollout', amount: 30000, status: 'open' },
        ],
      },
    ],
    documents: [
      { id: 'd-1', name: 'Master_Services_Agreement_2026.pdf', type: 'contract', uploadDate: '2026-01-05', size: '2.4MB' },
      { id: 'd-2', name: 'KYC_Verification_Form_US.pdf', type: 'kyc', uploadDate: '2026-01-05', size: '1.1MB' },
    ],
    auditNotes: [
      { id: 'n-1', timestamp: '2026-01-05 10:30', user: 'Finance Manager', message: 'Established account with standard 30-day terms and $120k initial credit cap.' },
      { id: 'n-2', timestamp: '2026-04-10 14:15', user: 'Super Admin', message: 'Invoice #15 paid late by 5 days, customer cited internal AP cycle delay. Keep terms unchanged.' },
    ],
    customFields: {
      'party-risk-rating': 'Low',
    },
    createdAt: '2026-01-05',
  },
  {
    id: 'p-glg',
    name: 'Global Logistics Group',
    code: 'DUAL-GLG',
    type: 'both', // DUAL role (tracks receivables and payables)
    status: 'active',
    baseCurrency: 'EUR', // Primary currency for this client/vendor is EUR
    taxId: 'EU-8839201',
    creditLimit: 75000,
    paymentTermsDays: 15,
    contacts: [
      { id: 'c-3', name: 'Dieter Braun', role: 'Global CFO', phone: '+49 89 2019 12', email: 'd.braun@glg-group.de' },
      { id: 'c-4', name: 'Marcella Rossi', role: 'Operations Lead', phone: '+39 02 8820 4', email: 'm.rossi@glg-it.org' },
    ],
    projects: [
      {
        id: 'proj-glg-logistics',
        name: 'Supply Chain Digital Optimization',
        milestones: [
          { id: 'm-glg-1', name: 'Discovery & Route Modeling', amount: 12000, status: 'billed' },
          { id: 'm-glg-2', name: 'API Services Deployment', amount: 18000, status: 'open' },
        ],
      },
    ],
    documents: [
      { id: 'd-3', name: 'Dual_Role_Reciprocal_MOU.pdf', type: 'contract', uploadDate: '2026-02-12', size: '1.8MB' },
    ],
    auditNotes: [
      { id: 'n-3', timestamp: '2026-02-12 11:00', user: 'Finance Manager', message: 'Dual-role enabled. Reciprocal ledger balance offset (Contra Entry) allowed up to lesser of of outstanding AR/AP.' },
    ],
    customFields: {
      'party-risk-rating': 'Medium',
    },
    createdAt: '2026-02-12',
  },
  {
    id: 'p-vertex',
    name: 'Vertex Software Agency',
    code: 'VEN-VERTEX',
    type: 'vendor',
    status: 'active',
    baseCurrency: 'USD',
    taxId: 'US-7739281',
    creditLimit: 50000,
    paymentTermsDays: 45,
    contacts: [
      { id: 'c-5', name: 'Ananya Nair', role: 'Client Partner', phone: '+91 80 4912 3912', email: 'ananya@vertex-soft.in' },
    ],
    projects: [],
    documents: [
      { id: 'd-4', name: 'Subcontractor_Framework_Agreement.pdf', type: 'contract', uploadDate: '2026-01-10', size: '3.1MB' },
    ],
    auditNotes: [
      { id: 'n-4', timestamp: '2026-01-10 16:45', user: 'Finance Manager', message: 'Strategic delivery subcontracting partner. Subject to 5% professional tax deduction on all payable transfers.' },
    ],
    customFields: {
      'party-risk-rating': 'Low',
    },
    createdAt: '2026-01-10',
  },
  {
    id: 'p-vanguard',
    name: 'Vanguard Creative Labs',
    code: 'CLI-VANGUARD',
    type: 'client',
    status: 'active',
    baseCurrency: 'AED',
    taxId: 'AE-3392831',
    creditLimit: 40000,
    paymentTermsDays: 30,
    contacts: [
      { id: 'c-6', name: 'Farah Al-Mansoori', role: 'Procurement Specialist', phone: '+971 4 291 3820', email: 'farah@vanguard.ae' },
    ],
    projects: [
      {
        id: 'proj-van-branding',
        name: 'Brand Identity Strategy',
        milestones: [
          { id: 'm-van-1', name: 'Initial Retainer - March', amount: 8000, status: 'billed' },
          { id: 'm-van-2', name: 'Initial Retainer - April', amount: 8000, status: 'billed' },
          { id: 'm-van-3', name: 'Initial Retainer - May', amount: 8000, status: 'billed' },
        ],
      },
    ],
    documents: [
      { id: 'd-5', name: 'Retainer_Creative_Agreement.pdf', type: 'contract', uploadDate: '2026-02-20', size: '1.4MB' },
    ],
    auditNotes: [
      { id: 'n-5', timestamp: '2026-02-20 09:12', user: 'Finance Manager', message: 'Fixed monthly creative retainer. Slow paying historical cycles; credit limit restricted to AED 40,000.' },
    ],
    customFields: {
      'party-risk-rating': 'High',
    },
    createdAt: '2026-02-20',
  },
  {
    id: 'p-orion',
    name: 'Orion Media Networks',
    code: 'CLI-ORION',
    type: 'client',
    status: 'blacklisted',
    baseCurrency: 'USD',
    taxId: 'US-4491029',
    creditLimit: 0,
    paymentTermsDays: 0,
    contacts: [
      { id: 'c-7', name: 'Marcus Sterling', role: 'Operations director', phone: '+1 555-339-1029', email: 'sterling@orion.com' },
    ],
    projects: [],
    documents: [
      { id: 'd-6', name: 'Legal_Demand_Default_Claim.pdf', type: 'other', uploadDate: '2026-05-10', size: '4.2MB' },
    ],
    auditNotes: [
      { id: 'n-6', timestamp: '2026-05-10 11:30', user: 'Super Admin', message: 'Blacklisted due to multi-month non-payment. Disputed balance of $12,500 written off as bad debt. Legal proceeding claims initiated.' },
    ],
    customFields: {
      'party-risk-rating': 'Critical',
    },
    createdAt: '2026-01-22',
  },
];

export const seedTransactions: Transaction[] = [
  // --- HISTORICAL STARTING POINT: 2026-01-01 ---
  {
    id: 'tx-ob-acme',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'opening_balance',
    referenceNumber: 'OPB-2026-01',
    transactionDate: '2026-01-01',
    dueDate: '2026-01-01',
    currencyCode: 'USD',
    amountInTxnCurrency: 15000,
    exchangeRate: 1.0,
    amountInBaseCurrency: 15000,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-01-01',
    createdBy: 'Super Admin',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
  {
    id: 'tx-ob-vertex',
    partyId: 'p-vertex',
    branchId: 'b-ny',
    transactionType: 'opening_balance',
    referenceNumber: 'OPB-2026-02',
    transactionDate: '2026-01-01',
    dueDate: '2026-01-01',
    currencyCode: 'USD',
    amountInTxnCurrency: -4500, // Negative for Payables
    exchangeRate: 1.0,
    amountInBaseCurrency: -4500,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-01-01',
    createdBy: 'Super Admin',
    customFields: { 'txn-cost-center': 'Engineering Services' },
  },

  // --- ACME ADVANCE COLLECTION: 2026-01-15 ---
  {
    id: 'tx-adv-acme',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'advance',
    referenceNumber: 'ADV-2026-001',
    transactionDate: '2026-01-15',
    dueDate: '2026-01-15',
    currencyCode: 'USD',
    amountInTxnCurrency: 10000, // advance inflow (reduces net outstanding client liability)
    exchangeRate: 1.0,
    amountInBaseCurrency: 10000,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Project Kickoff Advance for Cloud Architecture Upgrade',
    createdAt: '2026-01-15',
    createdBy: 'Finance Manager',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },

  // --- ACME INVOICES & PAYMENTS WITH TDS: FEB-APRIL 2026 ---
  {
    id: 'tx-inv-acme-1',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'milestone_invoice',
    referenceNumber: 'MSI-2026-101',
    transactionDate: '2026-02-10',
    dueDate: '2026-03-10',
    currencyCode: 'USD',
    amountInTxnCurrency: 15000, // Billed Blueprint Milestone
    exchangeRate: 1.0,
    amountInBaseCurrency: 15000,
    status: 'posted',
    projectId: 'proj-acme-cloud',
    milestoneId: 'm-acme-1',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-02-10',
    createdBy: 'Data Entry Operator',
    approvedBy: 'Finance Manager',
    approvedAt: '2026-02-11',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
  {
    id: 'tx-pmr-acme-1',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'payment_received',
    referenceNumber: 'PMR-2026-201',
    transactionDate: '2026-03-08',
    dueDate: '2026-03-08',
    currencyCode: 'USD',
    amountInTxnCurrency: 13500, // Net Payment after 10% TDS withholding
    exchangeRate: 1.0,
    amountInBaseCurrency: 13500,
    status: 'posted',
    tdsAmount: 1500, // TDS amount collected
    tdsRate: 10, // 10% Withholding Tax
    isDisputed: false,
    reconciledAt: '2026-03-08',
    comments: 'Acme paid Net amount; 10% withholding card presented.',
    createdAt: '2026-03-08',
    createdBy: 'Data Entry Operator',
    approvedBy: 'Finance Manager',
    approvedAt: '2026-03-08',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },

  // --- RECURRING RETAINER IN AED WITH EXCHANGE RATE CHANGES ---
  {
    id: 'tx-ret-vanguard-1',
    partyId: 'p-vanguard',
    branchId: 'b-dxb',
    transactionType: 'retainer',
    referenceNumber: 'RET-2026-301',
    transactionDate: '2026-03-01',
    dueDate: '2026-03-31',
    currencyCode: 'AED',
    amountInTxnCurrency: 15000,
    exchangeRate: 0.272, // 1 AED = 0.272 USD
    amountInBaseCurrency: 4080,
    status: 'posted',
    projectId: 'proj-van-branding',
    milestoneId: 'm-van-1',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-03-01',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },
  {
    id: 'tx-pmr-vanguard-1',
    partyId: 'p-vanguard',
    branchId: 'b-dxb',
    transactionType: 'payment_received',
    referenceNumber: 'PMR-2026-302',
    transactionDate: '2026-03-25',
    dueDate: '2026-03-25',
    currencyCode: 'AED',
    amountInTxnCurrency: 15000,
    exchangeRate: 0.272, // rate matches
    amountInBaseCurrency: 4080,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    reconciledAt: '2026-03-25',
    createdAt: '2026-03-25',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },

  // Retainer 2 (Unpaid, aged outstanding)
  {
    id: 'tx-ret-vanguard-2',
    partyId: 'p-vanguard',
    branchId: 'b-dxb',
    transactionType: 'retainer',
    referenceNumber: 'RET-2026-401',
    transactionDate: '2026-04-01',
    dueDate: '2026-05-01',
    currencyCode: 'AED',
    amountInTxnCurrency: 15000,
    exchangeRate: 0.272,
    amountInBaseCurrency: 4080,
    status: 'posted',
    projectId: 'proj-van-branding',
    milestoneId: 'm-van-2',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-04-01',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },

  // Retainer 3 (Unpaid, newer outstanding)
  {
    id: 'tx-ret-vanguard-3',
    partyId: 'p-vanguard',
    branchId: 'b-dxb',
    transactionType: 'retainer',
    referenceNumber: 'RET-2026-501',
    transactionDate: '2026-05-01',
    dueDate: '2026-05-31',
    currencyCode: 'AED',
    amountInTxnCurrency: 15000,
    exchangeRate: 0.273, // Slight forex fluctuation rate
    amountInBaseCurrency: 4095,
    status: 'posted',
    projectId: 'proj-van-branding',
    milestoneId: 'm-van-3',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: true, // Flagged as disputed by customer due to delivery query
    createdAt: '2026-05-01',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },

  // --- VERTEX VENDOR BILLS & POSTED PAYMENTS ---
  {
    id: 'tx-bil-vertex-1',
    partyId: 'p-vertex',
    branchId: 'b-ny',
    transactionType: 'bill',
    referenceNumber: 'BIL-2026-102',
    transactionDate: '2026-02-15',
    dueDate: '2026-03-31',
    currencyCode: 'USD',
    amountInTxnCurrency: -8000, // Negative for bills (owing money)
    exchangeRate: 1.0,
    amountInBaseCurrency: -8000,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'UI Resource Backfill Outsourcing Services',
    createdAt: '2026-02-15',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Engineering Services' },
  },
  {
    id: 'tx-pmm-vertex-1',
    partyId: 'p-vertex',
    branchId: 'b-ny',
    transactionType: 'payment_made',
    referenceNumber: 'PMM-2026-202',
    transactionDate: '2026-03-20',
    dueDate: '2026-03-20',
    currencyCode: 'USD',
    amountInTxnCurrency: 7600, // offsets bill debit/credit. Represent payment amount positive since it REDUCES owing balance.
    exchangeRate: 1.0,
    amountInBaseCurrency: 7600,
    status: 'posted',
    tdsAmount: 400, // We withheld 5% withholding professional tax on subcontractor
    tdsRate: 5,
    isDisputed: false,
    reconciledAt: '2026-03-20',
    comments: 'Paid Net to Vertex; 5% TDS deposited electronically.',
    createdAt: '2026-03-20',
    createdBy: 'Finance Manager',
    customFields: { 'txn-cost-center': 'Engineering Services' },
  },

  // --- DUAL-ROLE PARTY DYNAMIC OFFSETS (CONTRA ENTRY): EUR CURRENCY ---
  {
    id: 'tx-inv-glg-1',
    partyId: 'p-glg',
    branchId: 'b-ldn',
    transactionType: 'milestone_invoice',
    referenceNumber: 'INV-2026-801',
    transactionDate: '2026-04-10',
    dueDate: '2026-05-10',
    currencyCode: 'EUR',
    amountInTxnCurrency: 18000, // We performed routing research for GLG
    exchangeRate: 1.10, // 1 EUR = 1.10 USD
    amountInBaseCurrency: 19800,
    status: 'posted',
    projectId: 'proj-glg-logistics',
    milestoneId: 'm-glg-1',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-04-10',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
  {
    id: 'tx-bil-glg-1',
    partyId: 'p-glg',
    branchId: 'b-ldn',
    transactionType: 'bill',
    referenceNumber: 'BIL-2026-802',
    transactionDate: '2026-04-15',
    dueDate: '2026-04-30',
    currencyCode: 'EUR',
    amountInTxnCurrency: -10000, // They did inbound cargo for NY office
    exchangeRate: 1.10,
    amountInBaseCurrency: -11000,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-04-15',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
  {
    id: 'tx-cont-glg-1',
    partyId: 'p-glg',
    branchId: 'b-ldn',
    transactionType: 'journal_adjustment',
    referenceNumber: 'JV-2026-092',
    transactionDate: '2026-04-28',
    dueDate: '2026-04-28',
    currencyCode: 'EUR',
    amountInTxnCurrency: -10000, // Balance Mutual Offset (Contra Offset). 
    // It cancels out the EUR 10k payable entirely, while reducing the EUR 18k receivable to EUR 8k.
    // In details we show: debited Payable EUR 10k, credited Receivable EUR 10k.
    exchangeRate: 1.10,
    amountInBaseCurrency: -11000,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Reciprocal balance offset (Contra Entry): AR of €18k offset with AP of €10k. Net remaining AR is €8k.',
    createdAt: '2026-04-28',
    createdBy: 'Finance Manager',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },

  // --- ORION DEFAULT & BAD DEBT WRITE OFF: 2026-05-15 ---
  {
    id: 'tx-inv-orion-old',
    partyId: 'p-orion',
    branchId: 'b-ny',
    transactionType: 'invoice',
    referenceNumber: 'INV-2026-015',
    transactionDate: '2026-01-22',
    dueDate: '2026-02-22',
    currencyCode: 'USD',
    amountInTxnCurrency: 12500,
    exchangeRate: 1.0,
    amountInBaseCurrency: 12500,
    status: 'posted',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: true,
    createdAt: '2026-01-22',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },
  {
    id: 'tx-wro-orion',
    partyId: 'p-orion',
    branchId: 'b-ny',
    transactionType: 'journal_adjustment',
    referenceNumber: 'JV-2026-701',
    transactionDate: '2026-05-15',
    dueDate: '2026-05-15',
    currencyCode: 'USD',
    amountInTxnCurrency: -12500, // fully credits the receivable to zero out
    exchangeRate: 1.0,
    amountInBaseCurrency: -12500,
    status: 'written_off', // Specially marked written-off status as required by PRD 5.1.2
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Bad Debt Write-off authorized by Finance Committee. Customer in bankruptcy.',
    createdAt: '2026-05-15',
    createdBy: 'Super Admin',
    customFields: { 'txn-cost-center': 'Creative Dept' },
  },

  // --- ACTIVE PROJECTS MILESTONE INVOICING UNDERWAY ---
  {
    id: 'tx-inv-acme-2',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'milestone_invoice',
    referenceNumber: 'MSI-2026-102',
    transactionDate: '2026-04-15',
    dueDate: '2026-05-15',
    currencyCode: 'USD',
    amountInTxnCurrency: 25000, // Phase 2: Core Migration
    exchangeRate: 1.0,
    amountInBaseCurrency: 25000,
    status: 'posted',
    projectId: 'proj-acme-cloud',
    milestoneId: 'm-acme-2',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    createdAt: '2026-04-15',
    createdBy: 'Data Entry Operator',
    approvedBy: 'Finance Manager',
    approvedAt: '2026-04-16',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },

  // --- MAKER-CHECKER WORKFLOW QUEUE (NOT YET POSTED, PENDING CORRECTIONS OR APPROVALS) ---
  {
    id: 'tx-pending-acme-huge',
    partyId: 'p-acme',
    branchId: 'b-ny',
    transactionType: 'invoice',
    referenceNumber: 'INV-2026-NEW',
    transactionDate: '2026-06-12',
    dueDate: '2026-07-12',
    currencyCode: 'USD',
    amountInTxnCurrency: 15000, // Above approvalThreshold ($8000), must be pending_approval!
    exchangeRate: 1.0,
    amountInBaseCurrency: 15000,
    status: 'pending_approval',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Milestone 3 Integration phase draft invoice. Value exceeds basic portal threshold.',
    createdAt: '2026-06-12',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
  {
    id: 'tx-pending-vertex-journal',
    partyId: 'p-vertex',
    branchId: 'b-ny',
    transactionType: 'journal_adjustment',
    referenceNumber: 'JV-2026-PND',
    transactionDate: '2026-06-14',
    dueDate: '2026-06-14',
    currencyCode: 'USD',
    amountInTxnCurrency: -9500, // Above threshold, JV correction
    exchangeRate: 1.0,
    amountInBaseCurrency: -9500,
    status: 'pending_approval',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Manual adjustment to realign backfill software support logs.',
    createdAt: '2026-06-14',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Engineering Services' },
  },
  {
    id: 'tx-draft-glg-sub',
    partyId: 'p-glg',
    branchId: 'b-ldn',
    transactionType: 'bill',
    referenceNumber: 'BIL-2026-DFT',
    transactionDate: '2026-06-15',
    dueDate: '2026-07-15',
    currencyCode: 'EUR',
    amountInTxnCurrency: -4000,
    exchangeRate: 1.10,
    amountInBaseCurrency: -4400,
    status: 'draft',
    tdsAmount: 0,
    tdsRate: 0,
    isDisputed: false,
    comments: 'Waiting on supervisor signature validation before formal submission.',
    createdAt: '2026-06-15',
    createdBy: 'Data Entry Operator',
    customFields: { 'txn-cost-center': 'Delivery Unit 1' },
  },
];

export const seedAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'u-1',
    username: 'Super Admin',
    timestamp: '2026-06-15 09:00',
    action: 'SYSTEM_BOOTUP',
    details: 'Initial system seed database initialized with global currencies (USD, EUR, AED).',
    ipAddress: '192.168.1.5',
  },
  {
    id: 'log-2',
    userId: 'u-2',
    username: 'Finance Manager',
    timestamp: '2026-06-15 11:30',
    action: 'FISCAL_PERIOD_CLOSED',
    details: 'Closing accounting lock period set to 2026-03-31 for all operators.',
    ipAddress: '192.168.1.12',
  },
  {
    id: 'log-3',
    userId: 'u-3',
    username: 'Data Entry Operator',
    timestamp: '2026-06-15 14:02',
    action: 'DRAFT_TRANSACTION_CREATE',
    details: 'Created draft bill BIL-2026-DFT for EUR 4,000 against Global Logistics.',
    ipAddress: '192.168.12.98',
  },
];
